import { Router } from "express";
import authRoutes from "./auth.routes.js";
import userRoutes from "./user.routes.js";
import vendorRoutes from "./vendor.routes.js";
import productRoutes from "./product.routes.js";
import categoryRoutes from "./category.routes.js";
import cartRoutes from "./cart.routes.js";
import orderRoutes from "./order.routes.js";
import paymentRoutes from "./payment.routes.js";
import shippingRoutes from "./shipping.routes.js";
import reviewRoutes from "./review.routes.js";
import wishlistRoutes from "./wishlist.routes.js";
import messageRoutes from "./message.routes.js";
import notificationRoutes from "./notification.routes.js";
import searchRoutes from "./search.routes.js";
import couponRoutes from "./coupon.routes.js";
import referralRoutes from "./referral.routes.js";
import loyaltyRoutes from "./loyalty.routes.js";
import competitionRoutes from "./competition.routes.js";
import mediaRoutes from "./media.routes.js";
import blogRoutes from "./blog.routes.js";
import supportRoutes from "./support.routes.js";
import analyticsRoutes from "./analytics.routes.js";
import adminRoutes from "./admin.routes.js";
import aiRoutes from "./ai.routes.js";
import healthRoutes from "./health.routes.js";
import exportRoutes from "./export.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/vendors", vendorRoutes);
router.use("/products", productRoutes);
router.use("/categories", categoryRoutes);
router.use("/cart", cartRoutes);
router.use("/orders", orderRoutes);
router.use("/payments", paymentRoutes);
router.use("/shipping", shippingRoutes);
router.use("/reviews", reviewRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/messages", messageRoutes);
router.use("/notifications", notificationRoutes);
router.use("/search", searchRoutes);
router.use("/coupons", couponRoutes);
router.use("/referrals", referralRoutes);
router.use("/loyalty", loyaltyRoutes);
router.use("/competitions", competitionRoutes);
router.use("/media", mediaRoutes);
router.use("/blog", blogRoutes);
router.use("/support", supportRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/admin", adminRoutes);
router.use("/ai", aiRoutes);
router.use("/health", healthRoutes);
router.use("/export", exportRoutes);

export default router;
