import psycopg2
c = psycopg2.connect("postgresql://loopingon:loopingon_dev@localhost:5433/loopingon")
cur = c.cursor()
cur.execute("""UPDATE vendors SET "workshopCity" = 'Rambukkana', "workshopDistrict" = 'Kegalle' WHERE id = 'd7c0ae2a-8ac5-457f-a713-6d45fc4f6daa'""")
print("Location updated:", cur.rowcount)
c.commit()
cur.execute("""SELECT "storeName", "workshopCity", "workshopDistrict" FROM vendors WHERE id = 'd7c0ae2a-8ac5-457f-a713-6d45fc4f6daa'""")
r = cur.fetchone()
print(f"  {r[0]}: {r[1]}, {r[2]}")
cur.close()
c.close()
